# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.hostname = "asciiquarium"
  config.vm.provider "virtualbox" do |v|
    v.name = "asciiquarium"
    v.memory = 512
    v.cpus = 1
  end
  config.vm.provision "file", source: "./files/motd.txt", destination: "/home/vagrant/motd.txt"
  config.vm.provision "shell", path: "config.sh"
end
