# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.hostname = "lamp" 
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "lamp-setup.yaml"
  end
end

