# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.hostname = "husker"

  config.vm.provider "virtualbox" do |v|
    v.name = "husker"
		v.memory = 512
	  v.cpus = 1
  end

  config.vm.provision "ansible" do |a|
    a.playbook = "provision/vim-setup.yaml"
  end
end
