---
- name: Instalando PHP
  apt: name={{ item }} state=latest 
  with_items: "{{php_pkgs}}"

- name: Creando fichero prueba
  copy:
    src: ../files/info.php    
    dest: "{{web_path}}"
    owner: root
    group: root
    mode: 775

- name: Iniciando servicios
  service:
    name: apache2
    state: restarted
    enabled: yes
