---

#Incluyo las variables especificas del sistema operativo
- name: Incluyendo las variables del OS
  include_vars: "{{ ansible_os_family }}.yml"

#Incluyo el playbook que instala Gluster dependiendo del OS
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

#Creo el directorio del brick
- name: Creando directorios de brick
  file:
    path: "{{ gluster_brick }}"
    state: directory
    mode: 0775

#Configuro el primer volumen, que hará una replicación de los datos por todas
#las máquinas incluidas en el fichero hosts grupo gluster. Los host se
#emparejan automaticamente con gluster_volume
- name: Configurando volumenes
  gluster_volume:
    name: "{{ gluster_volume }}"
    bricks: "{{ gluster_brick }}"
    state: present
    replicas: 2
    cluster: 192.168.1.11,192.168.1.12
    force: yes
  run_once: true

