---
- name: Instalando prerequisitos
  apt:
    name: "{{ item}}"
    state: latest
    update_cache: yes
  with_items: "{{ gluster_pre }}"

- name: Añadiendo repositorio de Gluster
  apt_repository:
    repo: 'ppa:gluster/glusterfs-3.10'

- name: Instalando paquetes Gluster
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ gluster_pkgs }}"

- name: Iniciando servicio Gluster
  service:
   name: glusterfs-server
   state: started
   enabled: yes

#Abro en el firewall los puertos necesarios para la comunicación de los peers
- name: Abriendo puertos
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 111
    - 24007:24020
    - 49150:49160

- name: Reiniciando firewall
  service:
    name: ufw
    state: restarted

