---
- name: Instalando prerequisitos
  apt:
    name: "{{ item}}"
    state: latest
    update_cache: yes
  with_items: "{{ gluster_pre }}"

- name: Añadiendo repositorio de Gluster
  apt_repository:
    repo: 'ppa:gluster/glusterfs-3.8'

- name: Instalando paquetes Gluster
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ gluster_pkgs }}"

- name: Iniciando servicio Gluster
  service:
   name: glusterd
   state: restarted
   enabled: yes

#Abro en el firewall los puertos necesarios para la comunicación de los peers
- name: Abriendo puertos
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    zone: public
  with_items:
    - 111/tcp
    - 24007-24020/tcp
    - 49150-49160/tcp

- name: Reiniciando firewall
  service:
    name: firewalld
    state: restarted

