# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "hashicorp/precise32"

  N = 2

  (1..N).each do |machine_id|
    config.vm.define "gluster#{machine_id}" do |gluster|
      gluster.vm.hostname = "gluster#{machine_id}"
      gluster.vm.network "private_network", ip: "192.168.56.#{10+machine_id}"

      gluster.vm.provider "virtualbox" do |v|
        v.name = "gluster#{machine_id}"
      end

      if machine_id == N
        gluster.vm.provision "ansible" do |ansible|
          ansible.playbook = "example.yml"
          ansible.limit = 'all'
        end
      end

    end
  end
end
