# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04-i386"

  N = 2

  (1..N).each do |machine_id|
    config.vm.define "gluster#{machine_id}" do |gluster|
      gluster.vm.hostname = "gluster#{machine_id}"
      gluster.vm.network "private_network", ip: "192.168.56.#{1+machine_id}"

      gluster.vm.provider "virtualbox" do |v|
        v.name = "gluster#{machine_id}"
      end

      if machine_id == N
        gluster.vm.provision "ansible" do |a|
          a.playbook = "provision/gluster-setup.yaml"
          a.limit = 'all'
        end
      end

    end
  end
end
