# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04-i386"
  config.vm.hostname = "webserver"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.boot_timeout = 600
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider "virtualbox" do |v|
    v.name = "webserver"
  end

  config.vm.provision "ansible" do |a|
    a.playbook = "provision/webserver-setup.yaml"
  end
  
end
