---
- hosts: all
  become: yes
  tasks:
    - name: Instalando Apache
      apt:
        name: apache2
        state: latest
    - name: Iniciando el servicio de Apache
      service:
        name: apache2
        state: started
        enabled: yes
    - copy:
        src: files/welcome.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
