# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04-i386"
  config.vm.hostname = "lamp"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |v|
    v.name = "lamp"
  end

  config.vm.provision "ansible" do |a|
    a.playbook = "provision/lamp-setup.yaml"
  end

end

